import 'package:flutter/material.dart';

const List<Map<String, String>> categories = [
  {'label': 'Salud', 'value': 'healthcare'},
  {'label': 'Alojamiento', 'value': 'accommodation'},
  {'label': 'Actividades', 'value': 'activity'},
  {'label': 'Aeropuertos', 'value': 'airport'},
  {'label': 'Restaurantes', 'value': 'catering.restaurant'},
  {'label': 'Comida Rápida', 'value': 'catering.fast_food'},
  {'label': 'Educación', 'value': 'education'},
  {'label': 'Infantil', 'value': 'childcare'},
  {'label': 'Entretenimiento', 'value': 'entertainment'},
  {'label': 'Carreteras', 'value': 'highway'},
  {'label': 'Ocio', 'value': 'leisure'},
  {'label': 'Hecho por el Hombre', 'value': 'man_made'},
  {'label': 'Natural', 'value': 'natural'},
  {'label': 'Oficina', 'value': 'office'},
  {'label': 'Estacionamiento', 'value': 'parking'},
  {'label': 'Mascotas', 'value': 'pet'},
  {'label': 'Energía', 'value': 'power'},
  {'label': 'Producción', 'value': 'production'},
  {'label': 'Ferrocarril', 'value': 'railway'},
  {'label': 'Alquiler', 'value': 'rental'},
  {'label': 'Servicio', 'value': 'service'},
  {'label': 'Turismo', 'value': 'tourism'},
  {'label': 'Religión', 'value': 'religion'},
  {'label': 'Camping', 'value': 'camping'},
  {'label': 'Amenidad', 'value': 'amenity'},
  {'label': 'Playa', 'value': 'beach'},
  {'label': 'Adulto', 'value': 'adult'},
  {'label': 'Edificio', 'value': 'building'},
  {'label': 'Deportivo', 'value': 'sport'},
  {'label': 'Transporte Público', 'value': 'public_transport'},
];

const Map<String, IconData> categoryIcons = {
  'healthcare': Icons.local_hospital,
  'accommodation': Icons.hotel,
  'activity': Icons.directions_run,
  'airport': Icons.flight,
  'catering.restaurant': Icons.restaurant,
  'catering.fast_food': Icons.fastfood,
  'education': Icons.school,
  'childcare': Icons.child_friendly,
  'entertainment': Icons.movie,
  'highway': Icons.directions_car_filled,
  'leisure': Icons.pool,
  'man_made': Icons.handyman_outlined,
  'natural': Icons.park,
  'office': Icons.business,
  'parking': Icons.local_parking,
  'pet': Icons.pets,
  'power': Icons.bolt,
  'production': Icons.factory,
  'railway': Icons.train,
  'rental': Icons.place,
  'service': Icons.room_service,
  'tourism': Icons.camera_alt,
  'religion': Icons.church,
  'camping': Icons.terrain,
  'amenity': Icons.local_cafe,
  'beach': Icons.beach_access,
  'adult': Icons.explicit,
  'building': Icons.location_city,
  'sport': Icons.sports_soccer,
  'public_transport': Icons.directions_bus,
};
